name: Build & Release

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "meteor-addon-list.json"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      MAKE_LATEST: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto
      - name: Set version info
        id: version
        run: |
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          RUN_NUMBER=${{ github.run_number }}

          TAG_NAME="build-${RUN_NUMBER}"
          RELEASE_NAME="Release ${RUN_NUMBER}"
          JAR_NAME="mapart-exporter-${RUN_NUMBER}.jar"

          echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "release_name=$RELEASE_NAME" >> "$GITHUB_OUTPUT"
          echo "jar_name=$JAR_NAME" >> "$GITHUB_OUTPUT"
      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ steps.version.outputs.tag }} -m "${{ steps.version.outputs.release_name }}"
          git push origin ${{ steps.version.outputs.tag }}
      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew
      - name: Build addon
        run: ./gradlew build
      - name: Remove *-dev.jar
        run: rm ./build/libs/*-dev.jar || true
      - name: Rename jar
        run: |
          FILE=$(ls build/libs/*.jar | head -n 1)
          mv "$FILE" "build/libs/${{ steps.version.outputs.jar_name }}"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.release_name }}
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
